# Generated by Django 4.2.10 on 2026-03-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('benefits', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('IT', 'IT & Teknologji'), ('Marketing', 'Marketing & Shitje'), ('Finance', 'Financë & Kontabilitet'), ('Admin', 'Administratë'), ('Engineering', 'Inxhinieri'), ('Health', 'Shëndetësi'), ('Design', 'Dizajn & Kreativ'), ('Legal', 'Juridik'), ('Education', 'Arsim & Trajnim'), ('Other', 'Të Tjera')], max_length=20)),
                ('contract_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance / Projekt'), ('Internship', 'Praktikë')], default='Full-time', max_length=20)),
                ('experience', models.CharField(choices=[('Entry', 'Entry Level'), ('Junior', 'Junior (0–2 vjet)'), ('Mid', 'Mid-level (2–5 vjet)'), ('Senior', 'Senior (5+ vjet)'), ('Manager', 'Menaxher')], default='Mid', max_length=20)),
                ('location', models.CharField(choices=[('Tiranë', 'Tiranë'), ('Durrës', 'Durrës'), ('Vlorë', 'Vlorë'), ('Shkodër', 'Shkodër'), ('Elbasan', 'Elbasan'), ('Fier', 'Fier'), ('Remote', 'Remote')], max_length=60)),
                ('is_remote', models.BooleanField(default=False)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('cover_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'I Ri'), ('review', 'Në shqyrtim'), ('interview', 'Intervistë'), ('accepted', 'Pranuar'), ('rejected', 'Refuzuar')], default='new', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
